<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NetBox.Models\NetBox.Models.csproj" />
    <ProjectReference Include="..\NetBox.Data\NetBox.Data.csproj" />
    <ProjectReference Include="..\NetBox.Adapters\NetBox.Adapters.csproj" />
    <ProjectReference Include="..\XeniaManager.Core\XeniaManager.Core.csproj" />
    <ProjectReference Include="..\XeniaManager.Models\XeniaManager.Models.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>
</Project>
