import type { BladeSpec } from "./blade-types";

export const BLADES: BladeSpec[] = [
  {
    key: "bing",
    label: "bing",
    frameLeft: 198,
    frameTop: 11,
    frameWidth: 764,
    frameHeight: 368,
    tiles: [
      { id: "bing-search", x: 179, y: 123, w: 585, h: 92, title: "Search Xbox", background: "#c8000000" },
    ],
  },
  {
    key: "home",
    label: "home",
    frameLeft: 224,
    frameTop: 31,
    frameWidth: 834,
    frameHeight: 398,
    tiles: [
      { id: "home-open-tray", x: 0, y: 0, w: 185, h: 131, title: "Open Tray", image: "/assets/Assets/Misc/disc-tray.png", background: "#4e9a76" },
      { id: "home-pins", x: 0, y: 133, w: 185, h: 131, title: "My Pins", image: "/assets/Assets/Misc/pin.png", background: "#5aa785" },
      { id: "home-recent", x: 0, y: 266, w: 185, h: 131, title: "Recent", background: "#66b495" },
      { id: "home-halo", x: 187, y: 0, w: 466, h: 263, title: "Halo 4", image: "/assets/Assets/Tiles/halo4home.jpg" },
      { id: "home-dexter", x: 187, y: 265, w: 231, h: 133, title: "Dexter", image: "/assets/Assets/Tiles/dexterhome.jpg" },
      { id: "home-maroon5", x: 420, y: 265, w: 233, h: 133, title: "Maroon 5", image: "/assets/Assets/Tiles/maroon5home.jpg" },
      { id: "home-kinect", x: 655, y: 0, w: 179, h: 131, title: "Kinect Central", image: "/assets/Assets/Tiles/dancecentralhome.jpg" },
      { id: "home-sports", x: 655, y: 133, w: 179, h: 131, title: "Sports", image: "/assets/Assets/Tiles/espn.jpg" },
      { id: "home-youtube", x: 655, y: 266, w: 179, h: 131, title: "YouTube", image: "/assets/Assets/Tiles/youtubehome.jpg" },
    ],
  },
  {
    key: "social",
    label: "social",
    frameLeft: 224,
    frameTop: 31,
    frameWidth: 764,
    frameHeight: 368,
    tiles: [
      { id: "social-friends", x: 0, y: 0, w: 177, h: 122, title: "Friends", image: "/assets/Assets/Tiles/Social/friends.png", background: "#2f9a64" },
      { id: "social-themes", x: 0, y: 123, w: 177, h: 122, title: "Themes", image: "/assets/Assets/Misc/SettingsIcons/preferences.png", background: "#3f8a66" },
      { id: "social-signin", x: 0, y: 246, w: 177, h: 122, title: "Sign in or Out", image: "/assets/Assets/Tiles/Social/sign_in_or_out.png", background: "#459a70" },
    ],
  },
  {
    key: "video",
    label: "video",
    frameLeft: 236,
    frameTop: 73,
    frameWidth: 806,
    frameHeight: 301,
    tiles: [
      { id: "video-apps", x: 0, y: 3, w: 146, h: 148, title: "My Video Apps", image: "/assets/Assets/Tiles/Marketplace/my_video_apps_custom.png", background: "#397c5f" },
      { id: "video-market", x: 0, y: 153, w: 146, h: 148, title: "Video Marketplace", image: "/assets/Assets/Tiles/Marketplace/video_marketplace.png", background: "#3d8362" },
      { id: "video-feature", x: 148, y: 0, w: 308, h: 301, title: "The Dark Knight", image: "/assets/Assets/Tiles/thedarkkightvideo.jpg" },
      { id: "video-cloudy", x: 458, y: 0, w: 148, h: 150, title: "Cloudy", image: "/assets/Assets/Tiles/cloudywithachanceofmeatballsvideo.jpg" },
      { id: "video-recent", x: 608, y: 0, w: 198, h: 150, title: "Recent", background: "#ffffff" },
      { id: "video-kungfu", x: 458, y: 152, w: 148, h: 149, title: "Kung Fu Panda 2", image: "/assets/Assets/Tiles/kungfupanda2video.jpg" },
      { id: "video-hbogo", x: 608, y: 152, w: 198, h: 149, title: "HBO GO", image: "/assets/Assets/Tiles/hbogovideo.jpg" },
    ],
  },
  {
    key: "games",
    label: "games",
    frameLeft: 258,
    frameTop: 74,
    frameWidth: 759,
    frameHeight: 304,
    tiles: [
      { id: "games-my-games", x: 0, y: 0, w: 155, h: 153, title: "My Games", image: "/assets/Assets/Tiles/Marketplace/mygames.png", background: "#3b8465" },
      { id: "games-market", x: 0, y: 155, w: 155, h: 149, title: "Game Marketplace", image: "/assets/Assets/Tiles/Marketplace/game_marketplace.png", background: "#448d6c" },
      { id: "games-forza", x: 157, y: 0, w: 400, h: 303, title: "Forza Horizon", subtitle: "December IGN Pack", image: "/assets/Assets/Tiles/forzahorizongames.jpg" },
      { id: "games-minecraft", x: 559, y: 0, w: 200, h: 151, title: "Minecraft", image: "/assets/Assets/Tiles/minecraftgames.jpg" },
      { id: "games-blackops", x: 559, y: 153, w: 200, h: 150, title: "Black Ops II", image: "/assets/Assets/Tiles/blackops2games.jpg" },
    ],
  },
  {
    key: "music",
    label: "music",
    frameLeft: 236,
    frameTop: 76,
    frameWidth: 806,
    frameHeight: 298,
    tiles: [
      { id: "music-player", x: 0, y: 0, w: 148, h: 148, title: "Music Player", image: "/assets/Assets/Misc/music.png", background: "#428f67" },
      { id: "music-market", x: 0, y: 150, w: 148, h: 148, title: "Music Marketplace", image: "/assets/Assets/Tiles/Marketplace/music_marketplace.png", background: "#4b9a71" },
      { id: "music-feature", x: 150, y: 0, w: 306, h: 298, title: "Overexposed", subtitle: "Maroon 5", image: "/assets/Assets/Tiles/overexposedmusic.jpg" },
      { id: "music-recent", x: 458, y: 0, w: 158, h: 148, title: "Recent Music", image: "/assets/Assets/Tiles/evanescencerecent.png" },
      { id: "music-search", x: 618, y: 0, w: 188, h: 148, title: "search", background: "#191919" },
      { id: "music-panchiko", x: 458, y: 150, w: 348, h: 148, title: "Panchiko", image: "/assets/Assets/Tiles/panchikomusic.jpg" },
    ],
  },
  {
    key: "apps",
    label: "apps",
    frameLeft: 236,
    frameTop: 76,
    frameWidth: 806,
    frameHeight: 298,
    tiles: [
      { id: "apps-myapps", x: 0, y: 0, w: 148, h: 148, title: "My Apps", image: "/assets/Assets/Misc/myapps.png", background: "#3f8964" },
      { id: "apps-browse", x: 0, y: 150, w: 148, h: 148, title: "Browse Apps", image: "/assets/Assets/Tiles/Marketplace/apps_marketplace.png", background: "#48966d" },
      { id: "apps-hbogo", x: 150, y: 0, w: 306, h: 298, title: "HBO GO", image: "/assets/Assets/Tiles/hbogoapps.jpg" },
      { id: "apps-netflix", x: 458, y: 0, w: 158, h: 148, title: "Netflix", image: "/assets/Assets/Tiles/netflixapps.png" },
      { id: "apps-youtube", x: 618, y: 0, w: 188, h: 148, title: "YouTube", image: "/assets/Assets/Tiles/youtubeapps.jpg" },
      { id: "apps-hulu", x: 458, y: 150, w: 158, h: 148, title: "Hulu Plus", background: "#f4f4f4" },
      { id: "apps-espn", x: 618, y: 150, w: 188, h: 148, title: "ESPN", background: "#ffffff" },
    ],
  },
  {
    key: "settings",
    label: "settings",
    frameLeft: 224,
    frameTop: 31,
    frameWidth: 834,
    frameHeight: 398,
    tiles: [
      { id: "settings-system", x: 0, y: 0, w: 204, h: 204, title: "System", image: "/assets/Assets/Misc/SettingsIcons/system.png", background: "#45956f" },
      { id: "settings-preferences", x: 206, y: 0, w: 204, h: 204, title: "Preferences", image: "/assets/Assets/Misc/SettingsIcons/preferences.png", background: "#4d9c73" },
      { id: "settings-profile", x: 412, y: 0, w: 204, h: 204, title: "Profile", image: "/assets/Assets/Misc/SettingsIcons/account.png", background: "#54a97d" },
      { id: "settings-kinect", x: 618, y: 0, w: 204, h: 204, title: "Kinect", image: "/assets/Assets/Misc/SettingsIcons/kinect.png", background: "#4b9a70" },
      { id: "settings-family", x: 412, y: 206, w: 204, h: 192, title: "Family", image: "/assets/Assets/Misc/SettingsIcons/family.png", background: "#4a956d" },
      { id: "settings-turnoff", x: 618, y: 206, w: 204, h: 192, title: "Turn Off", image: "/assets/Assets/Misc/SettingsIcons/turnoff.png", background: "#3f8260" },
    ],
  },
];

export const TAB_POSITIONS = [
  { key: "bing", left: 180, width: 58 },
  { key: "home", left: 274, width: 78 },
  { key: "social", left: 388, width: 86 },
  { key: "video", left: 512, width: 82 },
  { key: "games", left: 634, width: 94 },
  { key: "music", left: 776, width: 88 },
  { key: "apps", left: 896, width: 68 },
  { key: "settings", left: 994, width: 128 },
];
